### PR TITLE
dlib whl file for py 10 11

### PR DESCRIPTION
**Pull request by rajan-poudel**
This changes give support for python version 10 & 11 as well . I have included the whl file of dlib for both python version 10 and 11 and also have update the md file accordingly.

Thank You ! :)

### CODE REVIEW

**Comment by kuttappayibiju2002** [comment]
i need dlib for python 3.12

**Comment by pinnintipraneethkumar** [comment]
> i need dlib for python 3.12

you get the dlib wheel for python3.12 here : https://github.com/z-mahmud22/Dlib_Windows_Python3.x

**Review by sachadee — APPROVED** [review]

**Review by sachadee — APPROVED** [review]
thanks!!!

**Review by sachadee — COMMENTED** [review]
thanks!!!

**Comment by Rahul-khetri** [comment]
i need dlib for python 3.11.5

**Comment by sachadee** [comment]
hi, i will check that

**Comment by mohsin-cs** [comment]
It's available on github bro

**Comment by sachadee** [comment]
https://github.com/z-mahmud22/Dlib_Windows_Python3.x

**Pull request merged**
